version: "3.7"

services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./:/home/app
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - test-net
    working_dir: /home/app
    tty: true
    dns:
      - 8.8.8.8
      - 8.8.2.2

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./public:/home/app/public
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - test-net
    ports:
      - "80:80"
    depends_on:
      - php

networks:
  test-net:
    external: true
