version: "3.7"

services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./:/home/app
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - test-net
    working_dir: /home/app
    tty: true
    dns:
      - 8.8.8.8
      - 8.8.2.2
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:alpine
    volumes:
      - ./public:/home/app/public
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - test-net
    ports:
      - "80:80"
    depends_on:
      - php

  elasticsearch:
    image: elasticsearch:5.6.14-alpine
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS= -Xms512m -Xmx512m"
    volumes:
      - elastic-storage:/usr/share/elasticsearch/data
    networks:
      - test-net
    ports:
      - "9200:9200"

volumes:
  elastic-storage:

networks:
  test-net:
    external: true
